language: php
dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

script:
  # Update composer to latest version.
  - composer self-update || true
  # Validate composer.json file.
  - composer validate
  # tests
  - vendor/bin/phpunit
